### ISSUE TITLE
Trouble with building "no ctypes_cstubs_internals.h"

### ISSUE THREAD

**Issue by herrlockskun** [orx/ocaml-orx#21]
Hello, 
When i tried to build the library with dune build got the following error : 
```
3 | (rule
14 |  (enabled_if
15 |   (<> %{ocaml-config:system} macosx))
....
28 |    %{ocaml_where}
29 |    -o
30 |    %{targets})))
orx_ml_types_stubgen.c:6:10: fatal error: ctypes_cstubs_internals.h: Aucun fichier ou dossier de ce type
    6 | #include "ctypes_cstubs_internals.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Do you any clues to solve this issue ? 
Thank you for your time.

**Comment by hcarty** [comment]
Hey @herrlockskun! I'm not sure what would lead to that error. Do you have both the `ctypes` and `ctypes-foreign` packages installed with `opam` in your current switch?

**Comment by herrlockskun** [comment]
Yes i have installed these with opam.

**Comment by herrlockskun** [comment]
Hey I have edited line 26 of the file ```src/types/stubgen/dune```. I changed  ```%{ocaml_where}/../ctypes``` by     ```%{ocaml_where}/ctypes```. 
Maybe ctypes changed and that's why it wasn't building.
Anyway this allow me to build.
I worked with ocaml  4.13.1 on ubuntu 22.04.
Thank you for you work
